version: '3.8'

services:
  api:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/dictionary-db
      - JWT_SECRET=supersecretjwt
    volumes:
      - .:/app
    command: npm run dev

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: